
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: notebook.ipynb

import time
from isolation import Board


# Credits if any
# 1) Textbook psuedocode
# 2)
# 3)

class OpenMoveEvalFn:
    def score(self, game, my_player=None):
        """Score the current game state
        Evaluation function that outputs a score equal to how many
        moves are open for AI player on the board minus how many moves
        are open for Opponent's player on the board.

        Note:
            If you think of better evaluation function, do it in CustomEvalFn below.

            Args
                game (Board): The board and game state.
                my_player (Player object): This specifies which player you are.

            Returns:
                float: The current state's score. MyMoves-OppMoves.

            """

        # TODO: finish this function!
        player_move_count = 0
        player_moves = game.get_player_moves(my_player)
        for move in player_moves:
            player_move_count+=1
        #print(player_move_count)
        opponent_move_count = 0
        opponent_moves = game.get_opponent_moves(my_player)
        for move in opponent_moves:
            opponent_move_count+=1
        #print(opponent_move_count)
        return player_move_count - opponent_move_count
        #return player_moves - opponent_moves
        #raise NotImplementedError





######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

class CustomPlayer:
    # TODO: finish this class!
    """Player that chooses a move using your evaluation function
    and a minimax algorithm with alpha-beta pruning.
    You must finish and test this player to make sure it properly
    uses minimax and alpha-beta to return a good move."""

    def __init__(self, search_depth=4, eval_fn=OpenMoveEvalFn()):
        """Initializes your player.

        if you find yourself with a superior eval function, update the default
        value of `eval_fn` to `CustomEvalFn()`

        Args:
            search_depth (int): The depth to which your agent will search
            eval_fn (function): Evaluation function used by your agent
        """
        self.eval_fn = eval_fn
        self.search_depth = search_depth

    def move(self, game, time_left):
        """Called to determine one move by your agent

        Note:
            1. Do NOT change the name of this 'move' function. We are going to call
            this function directly.
            2. Call alphabeta instead of minimax once implemented.
        Args:
            game (Board): The board and game state.
            time_left (function): Used to determine time left before timeout

        Returns:
            tuple: (int,int): Your best move
        """
        #best_move, utility = minimax(self, game, time_left, depth=self.search_depth)
        best_move, utility = alphabeta(self, game, time_left, depth=self.search_depth)
        return best_move

    def utility(self, game, my_turn):
        """You can handle special cases here (e.g. endgame)"""
        return self.eval_fn.score(game, self)

###################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE CLASS! ################
###### IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ###########
###################################################################


def minimax(player, game, time_left, depth, my_turn=True):
    """Implementation of the minimax algorithm.
    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you
            need from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer()).
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """

    # TODO: finish this function!

    #raise NotImplementedError
    #print(game)
    if my_turn == True:
        player = game.get_active_player()
        player_moves = game.get_player_moves(player)
        if depth == 0 or time_left == 0: #must terminate at depth = 0 or when the time is up
            return None, len(player_moves) - len(game.get_opponent_moves(player)) #need to return a null state/move
        best_move = None
        highest_value = -100000 #need a very small number that I know the board wont generate
        for move in player_moves:
            forecast = game.forecast_move(move)
            forecast_board = forecast[0]
            forecast_win = forecast[1]
            if forecast_win == True:
                #this means our tree has found a path to win
                return move, 100000
            output = minimax(player, forecast_board, time_left, depth-1, my_turn=False)
            if output[1] > highest_value:
                highest_value = output[1]
                best_move = move
        return best_move, highest_value
    elif my_turn == False:
        player = game.get_inactive_player() #grabs opponent to simulate moves
        opponent_moves = game.get_opponent_moves(player)
        if depth == 0 or time_left == 0:
            return None, len(game.get_player_moves(player)) - len(opponent_moves)
        best_move = None
        lowest_value = 100000
        for move in opponent_moves:
            forecast = game.forecast_move(move)
            forecast_board = forecast[0]
            forecast_win = forecast[1]
            if forecast_win == True:
                return move, -100000
            output = minimax(player, forecast_board, time_left, depth-1, my_turn=True)
            if output[1] < lowest_value:
                lowest_value = output[1]
                best_move = move
        return best_move, lowest_value

######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def alphabeta(player, game, time_left, depth, alpha=float("-inf"), beta=float("inf"), my_turn=True):
    """Implementation of the alphabeta algorithm.

    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you need
            from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer())
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        alpha (float): Alpha value for pruning
        beta (float): Beta value for pruning
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """

    # TODO: finish this function!
    #raise NotImplementedError
    if my_turn == True:
        player = game.get_active_player()
        player_moves = game.get_player_moves(player)
        if depth == 0 or time_left() < 100: #just return the best move we have if we run out of time/depth
            return None, player.utility(game, True)

        best_move = player_moves[0]
        highest_value = -100000 #need a value that I know the board wont generate
        for move in player_moves:
            forecast = game.forecast_move(move)
            forecast_board = forecast[0]
            forecast_win = forecast[1]
            if forecast_win == True:
                return move, 100000
            output = alphabeta(player, forecast_board, time_left, depth - 1, alpha, beta, my_turn=False)
            if output[1] > highest_value:
                highest_value = output[1]
                best_move = move
                alpha = max(alpha, highest_value)
                #alpha = output[1]

            if highest_value >= beta:
                return best_move, highest_value
        return best_move, highest_value
    elif my_turn == False:
        player = game.get_inactive_player()
        opponent_moves = game.get_opponent_moves(player)
        if depth == 0 or time_left() < 100:
            return None, player.utility(game, False)
        worst_move = opponent_moves[0]
        lowest_value = 100000
        for move in opponent_moves:
            forecast = game.forecast_move(move)
            forecast_board = forecast[0]
            forecast_win = forecast[1]
            if forecast_win == True:
                return move, -100000
            output = alphabeta(player, forecast_board, time_left, depth-1, alpha,beta, my_turn=True)
            if output[1] < lowest_value:
                lowest_value = output[1]
                worst_move = move
                beta = min(beta, lowest_value)
                #beta = lowest_value
            if lowest_value <= alpha:
                return worst_move, lowest_value
        return worst_move, lowest_value




######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
#tests.beatRandom(CustomPlayer)
#tests.minimaxTest(CustomPlayer, alphabeta)
#tests.playGame(CustomPlayer, alphabeta)
#ig = InteractiveGame(CustomPlayer, True)
# tests.name_of_the_test #you can uncomment this line to run your test

################ END OF LOCAL TEST CODE SECTION ######################


class CustomEvalFn:
    def __init__(self):
        pass

    def score(self, game, my_player=None):
        """Score the current game state.

        Custom evaluation function that acts however you think it should. This
        is not required but highly encouraged if you want to build the best
        AI possible.

        Args:
            game (Board): The board and game state.
            my_player (Player object): This specifies which player you are.

        Returns:
            float: The current state's score, based on your own heuristic.
        """

        # TODO: finish this function!
        raise NotImplementedError

######################################################################
############ DON'T WRITE ANY CODE OUTSIDE THE CLASS! #################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################